sql/220222_2차발표_SQL_1계정생성_2팀.sql, sql/220222_2차발표_SQL_2DB생성_2팀.sql, sql/220222_2차발표_SQL_3샘플데이터_2팀.sql, sql/sql문.sql
=> docs: add sql directory

sql/220312_SQL_2_DB_및_샘플데이터_생성_2팀.sql, sql/220312_SQL_4_notice_DB생성_및_샘플데이터_생성.sql, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAO.java, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAOImpl.java, src/main/java/com/kh/reading_fly/domain/comment/dto/CommentDTO.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVC.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/ApiCommentController.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/java/com/kh/reading_fly/web/form/comment/AddForm.java, src/main/java/com/kh/reading_fly/web/form/comment/ItemForm.java, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/detailForm.html, src/main/resources/templates/board/editForm.html, src/main/resources/templates/main/mainDetail.html
1. 게시판 댓글 등록 구현
2. 메인페이지 공지사항 링크 추가
3. sql문서의 notice, board 테이블 title칼럼 varchar2(50) -> varchar2(60)로 변경
=> 게시판 댓글 등록 구현

sql/220312_SQL_4_notice_DB생성_및_샘플데이터_생성.sql, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAOImpl.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/java/com/kh/reading_fly/web/controller/LoginController.java, src/main/java/com/kh/reading_fly/web/interceptor/CommentCheckInterceptor.java, src/main/resources/application.properties, src/main/resources/static/js/board/detailForm_old.js, src/main/resources/templates/board/detailForm.html
1. fragment 적용으로 인한 댓글 등록 오류 수정
=> 게시판 댓글 등록 수정

src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAOImpl.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVC.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/ApiCommentController.java, src/main/java/com/kh/reading_fly/web/form/comment/DetailForm.java, src/main/java/com/kh/reading_fly/web/form/comment/EditForm.java, src/main/resources/static/js/board/detailForm.js
1. 댓글 수정 버튼 클릭시 수정모드 전환
2. 이미 수정모드인 댓글은 읽기모드로 전환
=> 게시판 댓글 수정모드 구현

src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAO.java, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAOImpl.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVC.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/ApiCommentController.java, src/main/resources/static/js/board/detailForm.js
=> 게시판 댓글 수정 취소 구현

src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAO.java, src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAOImpl.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVC.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/resources/templates/board/listForm.html, src/main/resources/templates/fragment/mainDetail.html, src/test/java/com/kh/reading_fly/domain/board/dao/BoardDAOImplTest.java
=> 게시판 페이징 버튼 구현

src/main/resources/static/css/board/addForm.css, src/main/resources/static/css/board/detailForm.css, src/main/resources/static/css/board/editForm.css
=> 게시판 ckeditor css 수정

src/main/java/com/kh/reading_fly/web/form/qna/QnaAddForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaEditForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaReplyForm.java, src/main/resources/static/css/notice/noticeAddForm.css, src/main/resources/static/css/notice/noticeDetailForm.css, src/main/resources/static/css/notice/noticeEditForm.css, src/main/resources/static/css/qna/qnaAddForm.css, src/main/resources/static/css/qna/qnaDetailForm.css, src/main/resources/static/css/qna/qnaEditForm.css, src/main/resources/static/css/qna/qnaReplyForm.css, src/main/resources/static/js/notice/noticeAddForm.js, src/main/resources/static/js/notice/noticeDetailForm.js, src/main/resources/static/js/notice/noticeEditForm.js, src/main/resources/static/js/qna/qnaAddForm.js, src/main/resources/static/js/qna/qnaDetailForm.js, src/main/resources/static/js/qna/qnaEditForm.js, src/main/resources/static/js/qna/qnaReplyForm.js, src/main/resources/templates/notice/noticeAddForm.html, src/main/resources/templates/notice/noticeDetailForm.html, src/main/resources/templates/notice/noticeEditForm.html, src/main/resources/templates/qna/qnaAddForm.html, src/main/resources/templates/qna/qnaDetailForm.html, src/main/resources/templates/qna/qnaEditForm.html, src/main/resources/templates/qna/qnaReplyForm.html
=> 공지사항 Q&A ckeditor추가

src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAO.java, src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAOImpl.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVC.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVCImpl.java, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAO.java, src/main/java/com/kh/reading_fly/domain/comment/dao/CommentDAOImpl.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVC.java, src/main/java/com/kh/reading_fly/domain/comment/svc/CommentSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/ApiCommentController.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java
1. 게시판 및 댓글 메소드명 변경
2. 게시글 삭제, 게시글 본문 삭제 분리 구현
3. 댓글 삭제, 댓글 본문 삭제를 댓글 삭제 한 가지로 정리
=> 게시판 및 댓글 삭제 보완

src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/java/com/kh/reading_fly/web/form/board/AddForm.java, src/main/java/com/kh/reading_fly/web/form/board/EditForm.java, src/main/resources/errors.properties, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/editForm.html
=> 게시판 에러 메세지 구현

src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVC.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVCImpl.java, src/main/java/com/kh/reading_fly/domain/common/uploadFile/svc/UploadFileSVC.java, src/main/java/com/kh/reading_fly/domain/common/uploadFile/svc/UploadFileSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/java/com/kh/reading_fly/web/form/board/AddForm.java, src/main/java/com/kh/reading_fly/web/form/board/EditForm.java, src/main/resources/static/css/board/detailForm.css, src/main/resources/static/css/board/editForm.css, src/main/resources/static/js/board/editForm.js, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/detailForm.html, src/main/resources/templates/board/editForm.html, src/test/java/com/kh/reading_fly/domain/board/dao/BoardDAOImplTest.java
=> 게시판 파일첨부 구현

sql/notice&Q&A.sql, src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAO.java, src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAOImpl.java, src/main/java/com/kh/reading_fly/domain/board/dao/BoardFilterCondition.java, src/main/java/com/kh/reading_fly/domain/board/dao/BoardStatus.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVC.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVCImpl.java, src/main/java/com/kh/reading_fly/domain/common/uploadFile/dao/UploadFileDAOImpl.java, src/main/java/com/kh/reading_fly/domain/review/dao/ReviewDAO.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java, src/main/java/com/kh/reading_fly/web/controller/BookTestController.java, src/main/resources/static/js/board/listForm.js, src/main/resources/templates/board/listForm.html
=> 게시판 검색 기능 구현

src/main/java/com/kh/reading_fly/web/controller/NoticeController.java, src/main/java/com/kh/reading_fly/web/controller/QnaController.java, src/main/java/com/kh/reading_fly/web/form/notice/NoticeDetailForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaDetailForm.java, src/main/resources/static/js/notice/noticeDetailForm.js, src/main/resources/static/js/qna/qnaDetailForm.js, src/main/resources/templates/notice/noticeDetailForm.html, src/main/resources/templates/notice/noticeEditForm.html, src/main/resources/templates/qna/qnaDetailForm.html, src/main/resources/templates/qna/qnaEditForm.html, src/main/resources/templates/qna/qnaList.html, src/main/resources/templates/qna/qnaReplyForm.html
2. 상세 보기 목록 버튼 마지막 봤던 페이지로 이동
3. 답글에 답글 버튼 안 보이게
4. 답글 게시글 번호 안 보이게
=> 1. 첨부파일 수정 오류 해결

src/main/resources/templates/board/detailForm.html, src/main/resources/templates/fragment/mainDetail.html, src/main/resources/templates/fragment/uppermost.html
1. 어퍼모스트 my page란 삼항연산자 적용
2. 댓글창 삼항연산자 적용
=> 어퍼모스트, 댓글창 타임리프 삼항연산자 적용

src/main/resources/static/css/board/addForm.css, src/main/resources/static/css/board/detailForm.css, src/main/resources/static/js/board/addForm.js, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/detailForm.html, src/main/resources/templates/board/editForm.html
1. <br>태그 -> margin: 20px로 변경
2. 클래스명 - xx-area -> board-xx로 변경
=> 게시판 상세 페이지 css 변경

src/main/resources/errors.properties, src/main/resources/static/css/board/addForm.css, src/main/resources/static/css/main/mainDetail.css, src/main/resources/templates/board/addForm.html
1. 게시판 작성 페이지 css 적용
2. 에러 메세지 공통 css 적용
=> 게시판 작성 페이지 css 적용

src/main/resources/errors.properties, src/main/resources/static/css/board/editForm.css, src/main/resources/static/js/board/editForm.js, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/editForm.html
=> 게시판 수정 페이지 css 적용

src/main/java/com/kh/reading_fly/web/controller/NoticeController.java, src/main/java/com/kh/reading_fly/web/controller/QnaController.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaDetailForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaListForm.java, src/main/resources/static/css/notice/noticeAddForm.css, src/main/resources/static/css/notice/noticeDetailForm.css, src/main/resources/static/css/notice/noticeEditForm.css, src/main/resources/static/css/qna/qnaAddForm.css, src/main/resources/static/css/qna/qnaDetailForm.css, src/main/resources/static/css/qna/qnaEditForm.css, src/main/resources/static/js/notice/noticeAddForm.js, src/main/resources/static/js/qna/qnaAddForm.js, src/main/resources/static/js/qna/qnaDetailForm.js, src/main/resources/templates/notice/noticeAddForm.html, src/main/resources/templates/notice/noticeDetailForm.html, src/main/resources/templates/notice/noticeEditForm.html, src/main/resources/templates/qna/qnaAddForm.html, src/main/resources/templates/qna/qnaDetailForm.html, src/main/resources/templates/qna/qnaEditForm.html, src/main/resources/templates/qna/qnaList.html
=> 1. 날짜 형식 오늘이면 시간으로 변경

src/main/java/com/kh/reading_fly/web/controller/QnaController.java, src/main/resources/static/css/notice/noticeAddForm.css, src/main/resources/static/css/notice/noticeEditForm.css, src/main/resources/static/css/notice/noticeList.css, src/main/resources/static/css/qna/qnaAddForm.css, src/main/resources/static/css/qna/qnaEditForm.css, src/main/resources/static/css/qna/qnaList.css, src/main/resources/static/css/qna/qnaReplyForm.css, src/main/resources/static/js/qna/qnaReplyForm.js, src/main/resources/templates/qna/qnaReplyForm.html
=> 1. 답글 버튼 이벤트 처리

src/main/java/com/kh/reading_fly/domain/common/uploadFile/svc/UploadFileSVCImpl.java, src/main/resources/static/css/board/addForm.css, src/main/resources/static/css/board/detailForm.css, src/main/resources/static/css/board/editForm.css, src/main/resources/static/css/board/listForm.css, src/main/resources/static/css/main/mainDetail.css, src/main/resources/static/js/board/addForm.js, src/main/resources/static/js/board/editForm.js, src/main/resources/static/js/board/listForm.js, src/main/resources/templates/board/addForm.html, src/main/resources/templates/board/detailForm.html, src/main/resources/templates/board/editForm.html, src/main/resources/templates/board/listForm.html
=> 게시판 목록 페이지 css 적용

sql/reading_fly_DB.sql, src/main/java/com/kh/reading_fly/web/controller/MapController.java, src/main/resources/templates/map/map.html
=> MapController 추가

src/main/java/com/kh/reading_fly/web/controller/HomeController.java
=> 로그인시 /book/list 맵핑

src/main/java/com/kh/reading_fly/web/form/notice/NoticeAddForm.java, src/main/java/com/kh/reading_fly/web/form/notice/NoticeEditForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaAddForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaEditForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaReplyForm.java, src/main/resources/static/css/notice/noticeAddForm.css, src/main/resources/static/css/notice/noticeDetailForm.css, src/main/resources/static/css/notice/noticeEditForm.css, src/main/resources/static/css/notice/noticeList.css, src/main/resources/static/css/qna/qnaAddForm.css, src/main/resources/static/css/qna/qnaDetailForm.css, src/main/resources/static/css/qna/qnaEditForm.css, src/main/resources/static/css/qna/qnaList.css, src/main/resources/static/css/qna/qnaReplyForm.css, src/main/resources/static/js/notice/noticeAddForm.js, src/main/resources/static/js/qna/qnaAddForm.js, src/main/resources/static/js/qna/qnaReplyForm.js, src/main/resources/templates/notice/noticeAddForm.html, src/main/resources/templates/notice/noticeDetailForm.html, src/main/resources/templates/notice/noticeEditForm.html, src/main/resources/templates/notice/noticeList.html, src/main/resources/templates/qna/qnaAddForm.html, src/main/resources/templates/qna/qnaDetailForm.html, src/main/resources/templates/qna/qnaEditForm.html, src/main/resources/templates/qna/qnaList.html, src/main/resources/templates/qna/qnaReplyForm.html
2. 현재페이지 배경색 추가
3. 에러 메세지 수정, 본문 1000제한 없앰
4. 화면수정(main>.form으로 변경)
=> 1. 게시글 작성시 알림창

src/main/java/com/kh/reading_fly/web/form/notice/NoticeAddForm.java, src/main/java/com/kh/reading_fly/web/form/notice/NoticeEditForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaAddForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaEditForm.java, src/main/java/com/kh/reading_fly/web/form/qna/QnaReplyForm.java, src/main/resources/static/css/notice/noticeAddForm.css, src/main/resources/static/css/notice/noticeList.css, src/main/resources/static/css/qna/qnaList.css, src/main/resources/templates/notice/noticeList.html, src/main/resources/templates/qna/qnaList.html
=> 1. 에러 메세지 수정

src/main/java/com/kh/reading_fly/web/form/board/AddForm.java, src/main/java/com/kh/reading_fly/web/form/board/EditForm.java, src/main/resources/errors.properties, src/main/resources/static/css/board/detailForm.css, src/main/resources/static/css/board/listForm.css, src/main/resources/static/css/map/map.css, src/main/resources/static/js/map/map.js, src/main/resources/templates/board/listForm.html, src/main/resources/templates/map/map.html
=> 게시글 내용 1000자 제한 삭제

sql/reading_fly_DB.sql, src/main/java/com/kh/reading_fly/web/controller/member/FindController.java, src/main/resources/static/css/main/mainDetail.css, src/main/resources/static/css/map/map.css, src/main/resources/static/css/member/find/findIdForm.css, src/main/resources/static/css/member/find/findIdPwForm.css, src/main/resources/static/css/member/find/findPwForm.css, src/main/resources/static/css/member/login/loginForm.css, src/main/resources/static/css/member/signup/signupForm.css, src/main/resources/static/css/member/signup/signupSuccess.css, src/main/resources/static/js/member/find/findIdPwForm.js, src/main/resources/templates/fragment/mainDetail.html, src/main/resources/templates/map/map.html, src/main/resources/templates/member/find/findIdPwForm.html, src/main/resources/templates/member/find/findIdResult.html, src/main/resources/templates/member/find/findPwResult.html, src/main/resources/templates/member/login/loginForm.html, src/main/resources/templates/member/login/old/loginForm_old220409.html, src/main/resources/templates/member/signup/old/signupForm_old0220409.html, src/main/resources/templates/member/signup/signupForm.html, src/main/resources/templates/member/signup/signupSuccess.html
=> 로그인/회원가입/회원찾기 css 적용

sql/reading_fly_DB.sql, src/main/java/com/kh/reading_fly/domain/board/dao/BoardDAOImpl.java, src/main/java/com/kh/reading_fly/domain/board/svc/BoardSVCImpl.java, src/main/java/com/kh/reading_fly/domain/common/code/dao/CodeDAO.java, src/main/java/com/kh/reading_fly/domain/common/code/dao/CodeDAOImpl.java, src/main/java/com/kh/reading_fly/domain/common/code/dto/Code.java, src/main/java/com/kh/reading_fly/domain/common/code/dto/CodeAll.java, src/main/java/com/kh/reading_fly/domain/common/uploadFile/dao/UploadFileDAOImpl.java, src/main/java/com/kh/reading_fly/domain/common/uploadFile/dto/UploadFileDTO.java, src/main/java/com/kh/reading_fly/web/controller/BoardController.java
=> code 테이블 추가

src/main/java/com/kh/reading_fly/domain/notice/dao/NoticeDAOImpl.java, src/main/java/com/kh/reading_fly/domain/notice/svc/NoticeSVCImpl.java, src/main/java/com/kh/reading_fly/domain/qna/dao/QnaDAOImpl.java, src/main/java/com/kh/reading_fly/domain/qna/svc/QnaSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/NoticeController.java, src/main/java/com/kh/reading_fly/web/controller/QnaController.java, src/main/resources/templates/notice/noticeList.html, src/main/resources/templates/qna/qnaList.html
=> 1. code 수정

src/main/java/com/kh/reading_fly/domain/book/dao/BookDAO.java, src/main/java/com/kh/reading_fly/domain/book/dao/BookDAOImpl.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVC.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/APiBookController.java, src/main/resources/static/js/book/bookDetail.js, src/main/resources/templates/book/bookDetail.html
=> 독서 기록 등록 구현

src/main/java/com/kh/reading_fly/domain/book/dao/BookDAO.java, src/main/java/com/kh/reading_fly/domain/book/dao/BookDAOImpl.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVC.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/APiBookController.java, src/main/resources/static/js/book/bookDetail.js
1. 독서 기록 목록 구현
2. 독서 기록 총페이지 수정 구현
=> 독서 기록 목록 구현

src/main/java/com/kh/reading_fly/domain/book/dao/BookDAO.java, src/main/java/com/kh/reading_fly/domain/book/dao/BookDAOImpl.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVC.java, src/main/java/com/kh/reading_fly/domain/book/svc/BookSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/APiBookController.java, src/main/resources/static/js/board/detailForm.js, src/main/resources/static/js/book/bookDetail.js
=> 독서 기록 삭제 구현

src/main/java/com/kh/reading_fly/domain/calendar/dao/CalendarDAO.java, src/main/java/com/kh/reading_fly/domain/calendar/dao/CalendarDAOImpl.java, src/main/java/com/kh/reading_fly/domain/calendar/dto/CalendarDTO.java, src/main/java/com/kh/reading_fly/domain/calendar/svc/CalendarSVC.java, src/main/java/com/kh/reading_fly/domain/calendar/svc/CalendarSVCImpl.java, src/main/java/com/kh/reading_fly/web/controller/ApiCalendarController.java, src/main/java/com/kh/reading_fly/web/controller/CalendarController.java, src/main/resources/static/css/calendar/calendar.css, src/main/resources/static/js/calendar/calendar.js, src/main/resources/templates/calendar/calendar.html, src/main/resources/templates/fragment/mainDetail.html, src/main/resources/templates/main/main.html
=> 달력 dao,svc 구현
